"""Merge a LoRA adapter into the base model and write a standalone HF model.

Output is a drop-in replacement for the original pretrained_models dir — you
can pass it as `model_path` to `initiate_model()` and the full inference
pipeline works with no PEFT dependency at runtime.

Heavy non-LLM artifacts (flow, vocoder, speaker-embedding, etc.) are
symlinked rather than copied to save disk. To upload to HPC with the
symlinks resolved, use `rsync -L` or `tar -h`.

Usage:
    python scripts/lora/merge_adapter_to_base.py \\
        --adapter runs/hpc/adaptors3_avg/avg_11500_17000_22500 \\
        --base    pretrained_models/SoulX-Podcast-1.7B-dialect \\
        --out     pretrained_models/SoulX-Podcast-1.7B-dialect-avg \\
        --verify
"""

import sys as _sys
from pathlib import Path as _Path
_sys.path.insert(0, str(_Path(__file__).resolve().parents[2]))

import argparse
import shutil
import time
from pathlib import Path

import torch
import torchaudio
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer

# Heavy artifacts that are NOT touched by LoRA merging → symlink instead of copy.
SYMLINK_FILES = {
    "flow.pt",
    "flow.cache.pt",
    "flow.decoder.estimator.fp32.onnx",
    "hift.pt",
    "campplus.onnx",
}

# Small files that should be physically copied (so the merged dir is self-contained
# enough that losing the link target won't break it).
COPY_FILES = {
    "soulxpodcast_config.json",
    "tokenizer.json",
    "tokenizer_config.json",
    "vocab.json",
    "merges.txt",
    "added_tokens.json",
    "special_tokens_map.json",
    "README.md",
    ".gitattributes",
}

# These will be regenerated by merged.save_pretrained() and tokenizer.save_pretrained() —
# don't copy them from base.
REGENERATED = {
    "config.json",
    "generation_config.json",
    "model.safetensors.index.json",
}

VERIFY_PROMPT = {
    "speakers": {
        "S1": {
            "prompt_audio": "/notebooks/bert-vits2/frankenstein-matcha/ref123.wav",
            "prompt_text": "到咗落車嘅時候，連媽媽都走失埋。",
        }
    },
    "text": [
        ["S1", "<|Yue|>哈囉大家好啊，歡迎收聽我哋嘅節目。<|laughter|>今日我哋會傾下香港人最關心嘅事，住屋同埋通脹點樣影響緊我哋嘅生活。"]
    ],
}
VERIFY_SEED = 198964


def merge(adapter: Path, base: Path, out: Path):
    assert (base / "config.json").exists(), f"base model not found at {base}"
    assert (adapter / "adapter_config.json").exists(), f"adapter not found at {adapter}"
    assert not out.exists(), f"output dir {out} already exists — refuse to overwrite"
    out.mkdir(parents=True)

    print(f"[INFO] Loading base LLM from {base} (bfloat16)")
    base_llm = AutoModelForCausalLM.from_pretrained(str(base), torch_dtype=torch.bfloat16)
    tok = AutoTokenizer.from_pretrained(str(base))

    print(f"[INFO] Attaching adapter {adapter.name} and calling merge_and_unload()")
    peft_wrapped = PeftModel.from_pretrained(base_llm, str(adapter))
    merged = peft_wrapped.merge_and_unload()

    print(f"[INFO] Saving merged LLM weights -> {out}")
    merged.save_pretrained(str(out), safe_serialization=True)
    tok.save_pretrained(str(out))

    # Symlink the heavy non-LLM artifacts.
    for fname in sorted(SYMLINK_FILES):
        src = (base / fname).resolve()
        if not src.exists():
            print(f"[WARN] missing in base: {fname} (skipping)")
            continue
        dst = out / fname
        dst.symlink_to(src)
        print(f"[INFO] symlink {fname} -> {src}")

    # Copy the small support files.
    for fname in sorted(COPY_FILES):
        src = base / fname
        if not src.exists():
            print(f"[WARN] missing in base: {fname} (skipping)")
            continue
        dst = out / fname
        # tokenizer.save_pretrained may have already written some of these — skip those.
        if dst.exists():
            continue
        shutil.copy(src, dst)
        print(f"[INFO] copy {fname}")

    # Copy assets/ directory if present.
    if (base / "assets").exists():
        shutil.copytree(base / "assets", out / "assets", dirs_exist_ok=True)
        print("[INFO] copied assets/")

    # Free the merged model from GPU/CPU memory before the verify step
    # reloads via initiate_model() (which would otherwise OOM).
    del merged, peft_wrapped, base_llm
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    print(f"\n[DONE] Merged model written to {out}")


def verify(out_dir: Path, wav_path: Path):
    """Run a single inference with the merged model to confirm it's usable."""
    print(f"\n[INFO] Verification inference with merged model at {out_dir}")
    from soulxpodcast.utils.infer_utils import initiate_model, process_single_input
    from soulxpodcast.utils.parser import podcast_format_parser

    model, dataset = initiate_model(VERIFY_SEED, str(out_dir), "hf", fp16_flow=True)
    offset = model.config.hf_config.speech_token_offset
    print(f"[INFO] speech_token_offset = {offset}")

    inputs = podcast_format_parser(VERIFY_PROMPT)
    prepared = process_single_input(
        dataset,
        inputs["text"],
        inputs["prompt_wav"],
        inputs["prompt_text"],
        inputs["use_dialect_prompt"],
        inputs["dialect_prompt_text"],
    )

    torch.manual_seed(VERIFY_SEED)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(VERIFY_SEED)

    t0 = time.perf_counter()
    results = model.forward_longform(**prepared)
    elapsed = time.perf_counter() - t0

    wav = results["generated_wavs"][0].cpu()
    duration_s = wav.shape[-1] / 24000
    rtf = elapsed / duration_s if duration_s > 0 else float("nan")
    print(f"[INFO] generated {duration_s:.2f}s in {elapsed:.2f}s (RTF={rtf:.2f})")

    wav_path.parent.mkdir(parents=True, exist_ok=True)
    wav_to_save = wav.unsqueeze(0) if wav.dim() == 1 else wav
    torchaudio.save(str(wav_path), wav_to_save, 24000)
    print(f"[INFO] verify wav -> {wav_path}")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--adapter", type=Path, required=True, help="PEFT adapter dir to merge.")
    ap.add_argument("--base", type=Path, default=Path("pretrained_models/SoulX-Podcast-1.7B-dialect"),
                    help="Base pretrained-models dir.")
    ap.add_argument("--out", type=Path, required=True, help="Output dir for the merged model.")
    ap.add_argument("--verify", action="store_true", help="Run a verification inference after merging.")
    ap.add_argument("--verify-wav", type=Path, default=Path("outputs/lora_sweep/merged_verify.wav"),
                    help="Output wav path for --verify run.")
    args = ap.parse_args()

    merge(args.adapter, args.base, args.out)
    if args.verify:
        verify(args.out, args.verify_wav)


if __name__ == "__main__":
    main()
